// scripts/sampleData.js

// Dữ liệu mẫu cho User
const sampleUsers = [
  { name: 'Hùng Trịnh', role: 'admin' },
  { name: 'Diệp Khanh', role: 'admin' },
  { name: 'Lạc 🥜', role: 'admin' },
  { name: 'aleks', role: 'admin' },
  { name: 'Long Toe', role: 'admin' },
  { name: 'Minh Bảo Lê', role: 'admin' },
  { name: 'Chumin', role: 'admin' },
  { name: 'chị tým', role: 'admin' },
  { name: 'chấuuuu', role: 'admin' },
  { name: 'Chang Phạm', role: 'admin' },
  { name: 'khanh vịt', role: 'admin' },
  { name: 'Nam Anh', role: 'admin' },
  { name: 'Tú Anh', role: 'admin' },
  { name: 'Lan Lan', role: 'admin' },
  { name: 'Giang Bo', role: 'admin' },
  { name: 'Quân Hoàng', role: 'admin' },
  { name: 'Ninh Bùi', role: 'admin' },
  { name: 'Hoàng An', role: 'admin' },
  { name: 'HoangZiMel', role: 'admin' },
  { name: 'Hải Ly', role: 'admin' },
  { name: 'Kun', role: 'admin' },
  { name: 'ngân chuối', role: 'admin' },
  { name: 'Tiến Phú', role: 'admin' },
  { name: 'Khánh Cá', role: 'admin' },
  { name: 'An J', role: 'admin' }
];

// Dữ liệu mẫu cho Participant - Leaders
const sampleLeaders = [
  { name: 'Nguyễn Thị Hạnh Thục', type: 'leader' },
  { name: 'Lê Thuỳ Giang', type: 'leader' },
  { name: 'Trần Nhật Minh', type: 'leader' },
  { name: 'Phạm Tiến Đạt', type: 'leader' },
  { name: 'Nguyễn Trần Thảo Uyên', type: 'leader' },
  { name: 'Hoàng Hải Phong', type: 'leader' },
  { name: 'Nguyễn Trang Nhi', type: 'leader' },
  { name: 'Trần Hải Anh', type: 'leader' },
  { name: 'Hàn Tiến Quang', type: 'leader' },
  { name: 'Đào Hoàng Minh Tiến', type: 'leader' },
  { name: 'Phạm Hà Thu', type: 'leader' },
  { name: 'La Vũ Phong', type: 'leader' },
  { name: 'Nguyễn Minh Triết', type: 'leader' },
  { name: 'Lê Mỹ Tâm', type: 'leader' },
  { name: 'Nguyễn Thành Sơn', type: 'leader' },
  { name: 'Nguyễn Trần Lâm Tuệ', type: 'leader' },
  { name: 'Nguyễn Thị Ngân Hương', type: 'leader' },
  { name: 'Dương Hoàng Khánh Uyên', type: 'leader' },
  { name: 'Nguyễn Quốc Tuấn', type: 'leader' },
  { name: 'Lê Đặng Giang Chi', type: 'leader' },
  { name: 'Trần Quốc Việt', type: 'leader' },
  { name: 'Nguyễn Bảo Hưng', type: 'leader' },
  { name: 'Phan Ngọc Minh', type: 'leader' },
  { name: 'Nguyễn Hà Phương', type: 'leader' },
  { name: 'Tô Thanh Hằng', type: 'leader' },
  { name: 'Hàn Ngọc Minh', type: 'leader' },
  { name: 'Nguyễn Hà Phương', type: 'leader' },
  { name: 'Lê Đàm Minh Quang', type: 'leader' },
  { name: 'Phạm Hồng Thái Dương', type: 'leader' },
  { name: 'Tèo', type: 'leader' },
  { name: 'Bùi Khánh Linh', type: 'leader' },
  { name: 'Hoàng Hiếu Minh', type: 'leader' },
  { name: 'Đỗ Minh Huyền', type: 'leader' },
  { name: 'Nguyễn Thu Huyền', type: 'leader' },
  { name: 'Trần Chi Mai', type: 'leader' },
  { name: 'Diệp Hàn', type: 'leader' },
  { name: 'Nguyễn Quang Huy', type: 'leader' },
  { name: 'Phùng Tuấn Phong', type: 'leader' },
  { name: 'Nguyễn Ngọc Mỹ Phương', type: 'leader' },
  { name: 'Trần Giang Linh', type: 'leader' },
  { name: 'Trịnh Quỳnh Lam', type: 'leader' },
  { name: 'Nguyễn Thị Phương Nga', type: 'leader' },
  { name: 'Nguyễn Khánh Ngân', type: 'leader' },
  { name: 'Nguyễn Phương Linh', type: 'leader' },
  { name: 'Hoàng Quỳnh Minh Anh', type: 'leader' },
  { name: 'Trương Gia Hưng', type: 'leader' },
  { name: 'Trương Công Thái Đức', type: 'leader' },
  { name: 'Nguyễn Minh Phương', type: 'leader' },
  { name: 'Nguyễn Tuấn Minh', type: 'leader' },
  { name: 'Lê Ngân Hà', type: 'leader' },
  { name: 'Nguyễn Cao Ngọc An', type: 'leader' },
  { name: 'Đỗ Bảo Anh', type: 'leader' },
  { name: 'Tạ Huyền Trang', type: 'leader' },
  { name: 'Đoàn Mai Anh', type: 'leader' },
  { name: 'Lại Tuyết Mai', type: 'leader' },
  { name: 'Quản Phạm Gia An', type: 'leader' },
  { name: 'Nguyễn Linh Nhi', type: 'leader' },
  { name: 'Nguyễn Minh Ngọc', type: 'leader' },
  { name: 'Nguyễn Tài Bảo Anh', type: 'leader' },
  { name: 'Lê Minh Đạo', type: 'leader' },
  { name: 'Nguyễn Khánh', type: 'leader' },
  { name: 'Lưu Thị Lam Giang', type: 'leader' },
  { name: 'Nguyễn Tuấn Phước', type: 'leader' },
  { name: 'Nguyễn Thục Uyên', type: 'leader' },
  { name: 'nguyen van tien dung', type: 'leader' },
  { name: 'Nguyễn Tăng Hưng', type: 'leader' },
  { name: 'Lê Anh Khôi', type: 'leader' },
  { name: 'Mai Chi', type: 'leader' }
];

// Dữ liệu mẫu cho Participant - Supporters
const sampleSupporters = [
  { name: 'Đàm Trà My', type: 'supporter' },
  { name: 'Lê Hoàng Lan Nhi', type: 'supporter' },
  { name: 'Hoàng Hà Vy', type: 'supporter' },
  { name: 'Nguyễn Khánh Vân', type: 'supporter' },
  { name: 'Trần Minh Anh', type: 'supporter' },
  { name: 'Phạm Nguyên An', type: 'supporter' },
  { name: 'Trần Vương Bảo Khang', type: 'supporter' },
  { name: 'Triệu Khánh Chi', type: 'supporter' },
  { name: 'Hoàng Gia', type: 'supporter' },
  { name: 'Nguyễn Minh Quân', type: 'supporter' },
  { name: 'Nguyễn Thục Như', type: 'supporter' },
  { name: 'Vũ Thái An', type: 'supporter' },
  { name: 'Lê Diệu Linh', type: 'supporter' },
  { name: 'Nguyễn Ánh Ngọc', type: 'supporter' },
  { name: 'Trần An Thư', type: 'supporter' },
  { name: 'Ngô Uyên Linh', type: 'supporter' },
  { name: 'Phan Hà An', type: 'supporter' },
  { name: 'Nguyễn Phạm Khánh Phương', type: 'supporter' },
  { name: 'Nguyễn Gia Anh Duy', type: 'supporter' },
  { name: 'Chu Ngọc Minh Anh', type: 'supporter' },
  { name: 'Nguyễn Chí Hiển', type: 'supporter' },
  { name: 'Hoàng An Vy', type: 'supporter' },
  { name: 'Trần Nguyễn Chúc Khanh', type: 'supporter' },
  { name: 'Lê Khánh Chi', type: 'supporter' },
  { name: 'Nghiêm Phương Chi', type: 'supporter' },
  { name: 'Trần Minh Khuê', type: 'supporter' },
  { name: 'Lê Uyên Minh', type: 'supporter' },
  { name: 'Nguyễn Nam Việt', type: 'supporter' },
  { name: 'Nguyễn Vân San', type: 'supporter' },
  { name: 'Phạm Quỳnh Trang', type: 'supporter' },
  { name: 'Nguyễn Nam Khánh', type: 'supporter' },
  { name: 'Nguyễn Lê Nam Khánh', type: 'supporter' },
  { name: 'Lê Tuệ Minh', type: 'supporter' },
  { name: 'Nguyễn Hà Minh Châu', type: 'supporter' },
  { name: 'Nhữ Bình Minh', type: 'supporter' },
  { name: 'Đặng Đức Anh', type: 'supporter' },
  { name: 'Hoàng Khánh Uyên', type: 'supporter' },
  { name: 'Mai Ngọc Linh', type: 'supporter' },
  { name: 'Nguyễn Ngọc Cát Khuê', type: 'supporter' },
  { name: 'Hoàng Tùng Thư', type: 'supporter' }
];

// Kết hợp tất cả người tham gia
const sampleParticipants = [...sampleLeaders, ...sampleSupporters];

module.exports = {
  sampleUsers,
  sampleParticipants
};
